# Metody Numeryczne
# Zadanie laboratorium komputerowe 3.
# Rozwiązywanie układów równań liniowych

* Kamil Łangowski 
* Szymon Pawłowski 
* Przemysław Koden 




# Biblioteki

In [1]:
import numpy as np
import math 

# Kod eliminacji Gaussa

In [2]:
def gauss(A, Y):
  n = len(A)
  z = 0
  U = np.copy(A)
  for k in range(n-1):
    for i in range(k + 1, n):
      z = U[i][k]/U[k][k]
      U[i][k] = 0
      for j in range(k + 1, n):
        if (i == j) and ((U[i][j] - z*U[k][j]) == 0 or (U[i][j] - z*U[k][j]) == 0):
          return print("ERROR: Natrafiono na 0 na przekątnej")
        else:
          U[i][j] = U[i][j] - z*U[k][j]
  
  U_o = np.linalg.inv(U)
  L = np.dot(A, U_o)
  L_o = np.linalg.inv(L)

  print("Macierz A:", A, sep="\n")
  print("Macierz L:", L, sep="\n")
  print("Macierz U:", U, sep="\n")

  Z = np.empty(shape=(n,n)) 
  Z = np.dot(L_o, Y)

  X = np.empty(shape=(n,1))
  X = np.dot(U_o, Z)
  print("Rozwiazanie ukladu X:", X, sep="\n")


# Przykłady poprawnego działania bez wyboru wierszy głównych

In [3]:
A = np.array([[6, -2, 2, 4], [12, -8, 6, 10], [3, -13, 9, 3],[-6, 4, 1, -18]])
Y = np.array([[12],[34],[27],[-38]])
gauss(A, Y)

Macierz A:
[[  6  -2   2   4]
 [ 12  -8   6  10]
 [  3 -13   9   3]
 [ -6   4   1 -18]]
Macierz L:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  2.22044605e-16]
 [ 2.00000000e+00  1.00000000e+00  0.00000000e+00  4.44089210e-16]
 [ 5.00000000e-01  3.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-1.00000000e+00 -5.00000000e-01  2.00000000e+00  1.00000000e+00]]
Macierz U:
[[ 6 -2  2  4]
 [ 0 -4  2  2]
 [ 0  0  2 -5]
 [ 0  0  0 -3]]
Rozwiazanie ukladu X:
[[ 1.]
 [-3.]
 [-2.]
 [ 1.]]


In [4]:
A = np.array([[6, 2, 2], [2, 0.6667, 0.3333], [1, 2, -1]])
Y = np.array([[-2],[1],[0]])
gauss(A, Y)

Macierz A:
[[ 6.      2.      2.    ]
 [ 2.      0.6667  0.3333]
 [ 1.      2.     -1.    ]]
Macierz L:
[[ 1.00000000e+00  0.00000000e+00  1.02741708e-16]
 [ 3.33333333e-01  1.00000000e+00 -8.26978481e-18]
 [ 1.66666667e-01  5.00000000e+04  1.00000000e+00]]
Macierz U:
[[ 6.00000000e+00  2.00000000e+00  2.00000000e+00]
 [ 0.00000000e+00  3.33333333e-05 -3.33366667e-01]
 [ 0.00000000e+00  0.00000000e+00  1.66670000e+04]]
Rozwiazanie ukladu X:
[[ 2.599928]
 [-3.799904]
 [-4.99988 ]]


# Problem natrafienia na 0 na przekątnej

In [5]:
A = np.array([[6, -2, 2, 4], [24, -8, 6, 10], [3, -13, 9, 3],[-6, 4, 1, -18]])
Y = np.array([[12],[34],[27],[-38]])
gauss(A, Y)

ERROR: Natrafiono na 0 na przekątnej


In [6]:
A = np.array([[12, 10, -7], [6, 5, 3], [24, -1, 5],[24, -1, 5]])
Y = np.array([[15],[14],[28]])
gauss(A, Y)

ERROR: Natrafiono na 0 na przekątnej


# Problem dokonania zaokrągleń zmieniających wynik

In [7]:
A = np.array([[1,10**15],[1, 1]])
Y = np.array([[10**15], [2]])
gauss(A,Y) #poprawny wynik w przyblizeniu to (x,y)=(1, 1)

Macierz A:
[[               1 1000000000000000]
 [               1                1]]
Macierz L:
[[1. 0.]
 [1. 1.]]
Macierz U:
[[               1 1000000000000000]
 [               0 -999999999999999]]
Rozwiazanie ukladu X:
[[0.875]
 [1.   ]]


In [8]:
A = np.array([[10**(-23), 1], [1, 1]])
Y = np.array([[1],[2]])
gauss(A, Y) #poprawny wynik w przyblizeniu to (x,y)=(1,1)

Macierz A:
[[1.e-23 1.e+00]
 [1.e+00 1.e+00]]
Macierz L:
[[1.e+00 0.e+00]
 [1.e+23 1.e+00]]
Macierz U:
[[ 1.e-23  1.e+00]
 [ 0.e+00 -1.e+23]]
Rozwiazanie ukladu X:
[[0.]
 [1.]]


# Skalowany wybór wierszych głównych

In [9]:
A = np.array([[6, 2, 2], [2, 0.6667, 0.3333], [1, 2, -1]])
Y = [-2,1,0]

n = len(A)

s = []
p = []
il = []
temp = 0
specjal_j = 0
x = [0]*n

for i in range(0,n):

  p.append(i)
  s.append(i)

  for j in range(n-1):
    if (abs(A[i][j+1]) > abs(A[i][j])):
      s[i] = abs(A[i][j+1])
    else:
      s[i] = abs(A[i][j])


for k in range(0,n-1): 
    for i in range(k, n-1):
      temp1 = abs(A[p[k]][k])/s[p[k]]
      j = k
      if (abs(A[p[i]][k])/s[p[i]] > temp1):
        j = i
        #znalezienie j i przypisanie zmiennej pomocniczej jezeli warunek jest spełniony 
        temp1  = abs(A[p[i]][k])/s[p[i]]

    temp = p[j]
    p[j] = p[k] 
    p[k] = temp
    
    for i in range(k+1,n): 
      z = A[p[i]][k]/A[p[k]][k]
      A[p[i]][k] = 0
    for j in range(k+1, n):
      A[p[i]][j] = A[p[i]][j] - z*A[p[k]][j]
    

for k in range(0,n-1):
  for i in range(k+1,n):
    Y[p[i]] = Y[p[i]] - A[p[i]][k]*Y[p[k]]
for i in range(n-1, 0, -1):
  suma = 0
  for j in range(i,n-1):
    suma = suma + A[p[i]][j]*x[j]
  x[i] = ((Y[p[i]] - suma)/A[p[i]][i])


print(x)

[0, 1.4999250037498126, -0.0]
